//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTLPMQL.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Account
    {
        [Key]
        public int IDTaiKhoan { get; set; }
        [Required(ErrorMessage = "Tên Tài Khoản Không Chính Xác")]
        public string UserName { get; set; }
        [Required(ErrorMessage = "Mật Khẩu Không Chính Xác")]
        [DataType(DataType.Password)]
        public string Password { get; set; }
    }
}
